### ISSUE TITLE
Pulling 1 Error

### ISSUE THREAD

**Issue by Devarajan222** [pcyuen98/covidAPI#4]
Pulling 1 repository
Checkout conflict with files: 
covid-model/target/classes/com/app/entity/AreaEntity.class
covid-model/target/classes/com/app/entity/CountryEntity.class
covid-model/target/classes/com/app/entity/CovidCasesAreaEntity.class
covid-model/target/classes/com/app/entity/CovidCasesCountryEntity.class
covid-model/target/classes/com/app/entity/StateEntity.class
covid-model/target/classes/com/app/mapper/CountryMapper.class
covid-model/target/classes/com/app/mapper/CovidCasesAreaMapper.class
covid-model/target/classes/com/app/model/Area.class
covid-model/target/classes/com/app/model/Country.class
covid-model/target/classes/com/app/model/CovidCasesArea.class
covid-model/target/classes/com/app/model/State.class
covid-model/target/classes/com/app/model/api/Covid19ApiModel.class
covid-model/target/classes/com/app/util/BayiBotDefaultConstant.class
covid-model/target/classes/com/app/util/DateTools.class
covid-model/target/classes/com/app/util/ResffulServices.class
covid-model/target/classes/general.ucls
covid-model/target/classes/log4j.properties
covid-model/target/test-classes/CountryTest.class
covid-model/target/test-classes/date/Covid19ApiTest.class
covid-model/target/test-classes/date/DateTest.class
Checkout conflict with files: 
covid-model/target/classes/com/app/entity/AreaEntity.class
covid-model/target/classes/com/app/entity/CountryEntity.class
covid-model/target/classes/com/app/entity/CovidCasesAreaEntity.class
covid-model/target/classes/com/app/entity/CovidCasesCountryEntity.class
covid-model/target/classes/com/app/entity/StateEntity.class
covid-model/target/classes/com/app/mapper/CountryMapper.class
covid-model/target/classes/com/app/mapper/CovidCasesAreaMapper.class
covid-model/target/classes/com/app/model/Area.class
covid-model/target/classes/com/app/model/Country.class
covid-model/target/classes/com/app/model/CovidCasesArea.class
covid-model/target/classes/com/app/model/State.class
covid-model/target/classes/com/app/model/api/Covid19ApiModel.class
covid-model/target/classes/com/app/util/BayiBotDefaultConstant.class
covid-model/target/classes/com/app/util/DateTools.class
covid-model/target/classes/com/app/util/ResffulServices.class
covid-model/target/classes/general.ucls
covid-model/target/classes/log4j.properties
covid-model/target/test-classes/CountryTest.class
covid-model/target/test-classes/date/Covid19ApiTest.class
covid-model/target/test-classes/date/DateTest.class

**Comment by pcyuen98** [comment]
Do a git ignore target folder when commit 

Command - git add target .gitignore -f
