### ISSUE TITLE
output Date in browser is not same as output log

### ISSUE THREAD

**Issue by KahouTong** [pcyuen98/covidAPI#5]
![image](https://user-images.githubusercontent.com/60954865/111437467-1978c780-873e-11eb-8d23-a0ecb8bfabe7.png)

**Comment by pcyuen98** [comment]
Solution mentioned here 
https://stackoverflow.com/questions/56987681/date-value-mismatch-between-rest-server-and-postman 

Date changed to java.time.LocalDate
